#!/usr/bin/env python3

# COMP2041/9044 Assignment2
# grip-init
#
# This program was written by Melina Salardini (z5393518)
# on july 14, 2024
#
# it should create a an empty grip repository by creating a empty
# directory named .grip

import os
import sys

grip_dir = '.grip'

# check if the dir exists
if os.path.exists(grip_dir):
    print(f"grip-init: error: .grip already exists", file=sys.stderr)
    sys.exit(1)

# create a empty directory
try:
    os.mkdir(grip_dir)
    print(f"Initialized empty grip repository in .grip")

except Exception as e:
    print(f"grip-int: error: {e}", file=sys.stderr)
    sys.exit(1)